### ISSUE TITLE
c Nats Streaming 

### ISSUE THREAD

**Issue by BigJoe01** [nats-io/cnats#107]
Dear Nats Team,
Have any plan supporting nats stream with c library?

Best regards,

**Comment by ColinSullivan1** [comment]
@BigJoe01 ,  Thank you for your interest in NATS.  

We've seen some interest for a NATS streaming C client library and do plan to support this, but do not yet have a defined timeline.  

Would you mind describing your use case?

Thanks,
Colin

**Comment by BigJoe01** [comment]
Hi Colin,
Currently we using Kafka for durable messages in game services, but love homogeneous systems.
Primary development platform is c,c++.

Regards,
Joe

**Comment by scgm11** [comment]
any update on this? a C version for streaming ?
