### ISSUE TITLE
C++ 

### ISSUE THREAD

**Issue by nicknezis** [nats-io/cnats#109]
Any plans to add C++ support?

```c++
#ifdef __cplusplus
extern "C" {
#endif

// Nats C code

#ifdef __cplusplus
}
#endif
```

**Comment by kozlovic** [comment]
@nicknezis We have this in the `nats.h` so that it can be used with C++. Is that not working for you?

**Comment by nicknezis** [comment]
Sorry I totally overlooked that. Thanks!

**Comment by kozlovic** [comment]
It is in `nats.h` and `status.h`, but not in the adapters `libevent.h` and `libuv.h`, so I should add it there.
