### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by Kazmirchuk** [nats-io/cnats#111]
Hello,
First of all, thank you so much for cnats. The library's API looks very extensive and the design is clean. README and examples are pretty good too. Building it in Visual Studio worked like a charm.
Still the online help is limited to very brief descriptions of the API without any summary page that would describe how the library actually works under the hood. I'm developing a (hopefully robust) C++/Qt wrapper over cnats, and seeing how much work has been invested in thread safety, buffering, performance, thread pools, reconnections etc in cnats, I want to use this to full potential instead of restricting myself to minimal cnats API and re-doing all these things myself using Qt.

This wrapper will be used in a large and multi-threaded application, so this is what I'm wondering about:
1. Is the library thread-safe? can I create a connection/subscription/statistics in one thread, use it in another and destroy in a third thread? I see you already have an answer here https://github.com/nats-io/cnats/issues/50 but it would be nice to have documented.
2. How do threads and subscription buffers work? You partially answer this here https://github.com/nats-io/cnats/issues/59 but a more complete description would be nice.
2.1. On the publisher's side, it is unclear what is the purpose of natsConnection_Flush. All examples always use it. Should I use it too? Should I flush after every message? If I just want to flush the I/O buffer, why do I need to wait till gnatsd replies with a pong? or simply use natsOptions_SetSendAsap? If I don't use it, how much time my messages will wait before being sent? 
Finally, what if I publish messages too fast for cnats to send them over network - will the buffer grow indefinitely? Can I query for a number of outgoing messages in the buffer?
2.2. On the (async) subscriber's side, is my understanding correct that the library starts a new thread to read data from a socket as fast as possible, store it in a buffer and then pass to a callback's thread? So, the "Slow consumers" scenario as described here http://nats.io/documentation/server/gnatsd-prune/ is not possible with cnats, but rather replaced with NATS_SLOW_CONSUMER, correct?

3. If you have natsOptions_UseOldRequestStyle, what is the new request style then? I can see how it works over network with gnatsd -DV though. Does it mean that if many services reply to a request, gnatsd will send all replies to the requestor, and then cnats will deliver the first reply and discard the rest? and with the old style this work is performed by gnatsd? 

4. Do I need to use nats_ReleaseThreadMemory only when I integrate cnats with an event loop, or when doing any kind of publishing or subscribing in a background thread?

5. What does this comment means in one of your examples?
// For maximum performance, set no limit on the number of pending messages.
s = natsSubscription_SetPendingLimits(sub, -1, -1);
How do the limits affect performance?

6. I am running the "nats-subscriber" example with -count 30 and "nats-publisher" with -count 30 (both on the same Windows 7 host, no TLS, MSVC x64). After running the publisher, this is what I get in console output of the subscriber:
In Msgs:        30 - In Bytes:       150 - Delivered: -3689348814741910324 - Pending:     0 - Dropped:     0 - Reconnected:   0
I think, the number of delivered messages got wrong somehow?

7. Some summary about how reconnection works, also in a cluster environment, would be useful too IMHO. I think I can derive this information from careful reading of all related API functions, but still I can miss something.

Thanks in advance.

**Comment by Kazmirchuk** [comment]
An explanation of robust error handling to handle all possible network failures and race conditions would be immensely useful too, I think.

**Comment by kozlovic** [comment]
@Kazmirchuk I added a FAQ section in the README, hope this helps a bit with some of your questions.

Specifically regarding some of your questions here:

>If you have natsOptions_UseOldRequestStyle, what is the new request style then? 

There is no API to trigger the new style, it is now the default. The new style improves performance by reducing the number of subscriptions created when doing requests/replies. A single inbox subscription is created per connection and replies are then matched to the appropriate request.

>What does this comment means in one of your examples?
// For maximum performance, set no limit on the number of pending messages.
s = natsSubscription_SetPendingLimits(sub, -1, -1);
How do the limits affect performance?

When the publisher publishes as fast as it can, the subscription may fall behind since it is always slower to process a subscribed message than send a message. In order for the example/benchmark to not lose messages and ensure that the subscription will process all sent messages, I set the subscription's queue limits to "unlimited".

> In Msgs: 30 - In Bytes: 150 - Delivered: -3689348814741910324 - Pending: 0 - Dropped: 0 - Reconnected: 0
I think, the number of delivered messages got wrong somehow?

I can reproduce this on Windows, I will have a look and create separate issue. Thanks!

**Comment by Kazmirchuk** [comment]
Wow that was quick! Good to know that the negative counter was not a bug in cnats itself.
Thank you so much for the FAQ. It hasn't appeared yet at the main page https://github.com/nats-io/cnats (I guess it needs some time), but I can already read it in the git commit - it is very useful and much more than I could ever expect. Kudos!

**Comment by kozlovic** [comment]
@Kazmirchuk Thanks! I was waiting to get some feedback from you, which apparently is pretty good ;-). I have merged the PR so the FAQ section should now be present in the repo's README at [this location](https://github.com/nats-io/cnats#faq).
