### ISSUE TITLE
define adapter/libevent.h functions as static function.

### ISSUE THREAD

**Issue by FengMInng** [nats-io/cnats#121]
the head file adapter/libevent.h can't include more times, else LD failed.

**Comment by kozlovic** [comment]
The file is surrounded with

```
#ifndef LIBEVENT_H_
#define LIBEVENT_H_
...
#endif /* LIBEVENT_H_ */
```
which allows for the file to be included many times but declare things only once. Not sure what issue you are actually reporting.

Would you mind providing steps to reproduce the issue?

Thanks!

**Comment by FengMInng** [comment]
I  have a local header file include "adapter/libevent.h", and at source file a.c, b.c include my local header file.
compile is success, but when I link a.o and b.o as a program, then failed because for redefine functions.

**Comment by kozlovic** [comment]
You should use the same principle of defining a tag for your header file so it is included only once.
I see that you closed the issue, was it resolved or did you close by mistake?
