### ISSUE TITLE
nats_Open() fails after nats_Close()

### ISSUE THREAD

**Issue by hidai** [nats-io/cnats#124]
Since `nats_Open` uses InitOnce, the following code doesn't work.
```
nats_Open(-1);
...
nats_Close();
...
nats_Open(-1);  // fail!
```

In my project, it's almost impossible to call `nats_Close` at the end of the program (for exampe, `atexit`), but I don't want to leak memory (We have leak check in our CI). My solution was calling `nats_Close` at the destructor of my NatsClient class, but with that solution, I can't create the second NatsClient object after the first one's destruction.

Is there any way to do the open-close-open-close sequence appropriately?

**Comment by kozlovic** [comment]
@hidai It should work, I believe I even have tests for that. What type of failure do you get?

**Comment by hidai** [comment]
Sorry, @kozlovic, you're right.
My issue was different. It seems a concurrency issue. I'm closing this issue, and will open another one with reproducible code.
