### ISSUE TITLE
nats_Open and nats_Close can't run simultaneously

### ISSUE THREAD

**Issue by hidai** [nats-io/cnats#125]
The following code often fails in my Linux (Ubuntu 16.04) environment.
```
#include <nats.h>
#include <thread>
#include <iostream>

static void sub() {
    natsStatus s = nats_Open(-1);
    if (s != NATS_OK) {
        std::cout << "Open failed: " << natsStatus_GetText(s) << std::endl;
    } else {
        nats_Close();
    }
}

int main() {
    std::thread th(sub);
    sub();
    th.join();

    return 0;
}
```
Error message will be:
```
% g++ -std=c++11 -Wall -I ../src foo.cpp -Lsrc -lnats_static -lpthread  &&  ./a.out
Open failed: Initialization Failed
```

Guarding both `nats_Open` and `nats_Close` with mutex lock fixes the issue.

Is that expected? If mutex lock is necessary by spec, the document should be updated so.

**Comment by kozlovic** [comment]
@hidai It does not make sense to me to be calling `nats_Open` and/or `nats_Close` *concurrently*.

Think about it. You would have code running trying to open the library, do some NATS operations, while another part of your code would be closing it? What does that say about the application?

Adding a lock in the library would mean that  the lock would need to survive the close, which then would be reported as memory in use (which some will report as memory leak, which is not). So if need be I will then document that these should not be called concurrently.

**Comment by hidai** [comment]
Now I think that my problem should be addressed not by the library side but by the user side.
But let me explain what I wanted to do here since this might be useful for other users who  have similar use-case with me.
The problem I was trying to deal with is Case 3 in the figure below.

**Case 1**
```
client A      A--------->|
client B            B----------->|
opened?       |<---------------->|
              ^                  ^
              |                  |
              nats_Open          nats_Close
```
**Case 2**
```
client A      A--------->|
client B                      B----------->|
opened?       |<-------->|    |<---------->|
              ^          ^    ^            ^
              |          |    |            |
              nats_Open  |    nats_Open    |
                         nats_Close        nats_Close
```
**Case 3**
```
client A      A--------->|
client B                 B----------->|
opened?       |<-------->|<---------->|
              ^          ^
              |          |
              nats_Open  !!race condition!!
                         nats_Close and nats_Open are called concurrently
```

The race condition can be properly handled by user side using an integer counter and a mutex like below.
```
class Nats {
public:
    Nats() {
        std::lock_guard<std::mutex> lock(m);
        nats_Open(-1);
        ++c;
    }

    ~Nats() {
        std::lock_guard<std::mutex> lock(m);
        if (c == 1) {
            nats_Close();
        }
        --c;
    }

private:
    static int c = 0;
    static std::mutex m;
};
```
