### ISSUE TITLE
The threading model is not described very clearly in the Github README

### ISSUE THREAD

**Issue by p1-mmr** [nats-io/cnats#126]
Hello,

If I understand well, using cnats:
* There is one cnats-managed "reading thread" per *connection*, but it can be substituted with an user event loop using `natsOptions_SetEventLoop`,
* There is one cnats-managed "dispatcher thread" per *subscription*, but it can't be substituted with an user event loop (this number can only be reduced reduced using a cnats-managed thread pool),
* There is one cnats-managed "flusher thread" per *connection*, but it can't be substituted with an user event loop (unsure for this one)

I think I would be good to present the threading model of the library more clearly in the Github README, because the information is currently scattered across it, and could be presented in a somewhat more helpful manner for complex systems design.

For example, I have first thought that the "reading thread" and "dispatching thread" were the same thing and that cnats would allow me to fully control the threading model of my program through `natsOptions_SetEventLoop` (I thought that the user could specify a fixed number of threads containing each an event loop where I could submit, for instance, both NATS-originated and timer-originated processing tasks, which would imply that I could manage the threads and the event loops myself - this model is not possible with cnats as far as I understand).

Anyway, the API design is generally very good and it seems to be fast, so thanks for maintaining this great library.

**Comment by p1-mmr** [comment]
As a side note, something that would be useful, too, would be to be able to initialize something in the context of a "dispatcher thread", without waiting for traffic for come: this would be useful, for example, for people making use of libraries or code keeping thread-local context.

**Comment by kozlovic** [comment]
@p1-mmr Thank you for your interest. Just a quick note to let you know that I will be looking into this a bit later. A quick answer to your questions:
* Yes, there is a thread per connection (the `readLoop`) unless you set an external event loop (usually `libuv` or `libevent`, but you could build your own adapter as long as you implement the required hooks).
* Yes, there is by default 1 thread per async subscription. The `readLoop` thread dequeues messages from the socket and move them to the corresponding subscriber's internal queue from which the `natsSub_deliverMsgs` thread dequeue them and invoke the subscription's callback. Again, there is an option to use a library level thread pool to do that. So you can limit the number of threads if you have a lot of async subscriptions.
* True, there is one `flusher` thread per connection. Its responsibility is to flushed (write to the socket) accumulated data in the connection write buffer. There is currently no option to not have this thread running.

Regarding your side note, are you suggesting that you would like to pass some init function when creating an async subscription and that this init function would be invoked before starting the dispatch loop in the `deliverMsgs` thread?

**Comment by kozlovic** [comment]
A bit confused, but something that we will not do is having the invocation of the subscription's callback from the readLoop. The readLoop gets data for the connection, you do not want to block this with invocation of a message callback that is user code. If that is a bit slow, the server will probably disconnect the server. This is the reason we have different threads for reading out of the socket and dispatching messages to users.

**Comment by p1-mmr** [comment]
Ok you're right. So this is more like a structural incompatibility with our kind of code base (which may be reasonable to most people).
