### ISSUE TITLE
C Nats streaming client

### ISSUE THREAD

**Issue by santiviglione** [nats-io/cnats#140]
Hello Im working on an IoT project and NATS seems a perfect fit but streaming is a must so we dont loose any message, any plans for c streaming client lib? I think would be great for IoT projects

**Comment by cpowersrbr** [comment]
I'm also keen on this.
See also Issue 102 under go-nats-streaming.

**Comment by loint** [comment]
I'm planning to use Nats Streaming for our micro-service system as event bus with C++

**Comment by kozlovic** [comment]
Just released today as beta release. If feedback regarding API is ok (or no feedback), then we will get out of beta status. Thanks for your patience and interest in the C client!

**Comment by kozlovic** [comment]
Wondering if people interested in the NATS Streaming C Client had a chance to evaluate the 1.8.0-beta release. If so, did you find any API design issue that should be addressed before getting out of beta status? If no answer, I may release 1.8.0 this week. Thanks!

**Comment by Kazmirchuk** [comment]
Hi,
I just wanted to say a huge THANK YOU for your hard work, and even though in my company we are still pretty happy with the (basic) NATS, there is a chance we'll start using NATS Streaming in future. So, I can reassure you that there is a community of C/C++ developers using NATS in production.

**Comment by kozlovic** [comment]
@Kazmirchuk That's very kind of you!
