### ISSUE TITLE
Retry on initial connect unblocked

### ISSUE THREAD

**Issue by fmvin** [nats-io/cnats#155]
This is continue of #148.  The solution for #148 blocks the thread on `natsConnection_Connect()` forever or depends of values `natsOptions_SetMaxReconnect()`, `natsOptions_SetReconnectWait()` are set up.

Is it possible to process  `natsConnection_Connect()` asynchronously and call reconnection callback, for example, if client successfully connects to server?

**Comment by kozlovic** [comment]
How would the connection calls behave while the connection is not connected then? For instance, at the moment, a publish call checks that the message size is not greater than the max payload, value which we get only from the INFO of the server we connect to. I could of course disable this test, or fail all connection tests until the connection is first connected, or buffer (as in reconnect) while the library tries to connect.

Also, should the connect then return OK while trying to connect in the background or return an error, say NATS_NOT_YET_CONNECTED?

The feature is in master but no release was made yet, so I could change the semantic no problem. The thing is I am not sure how things should behave if I allow async connect.

**Comment by fmvin** [comment]
> Also, should the connect then return OK while trying to connect in the background or return an error, say NATS_NOT_YET_CONNECTED?

Just OK cause a misunderstanding for user because connection is not really established.  `NATS_NOT_YET_CONNECTED` looks good.

Also I think it will be good idea to support async, sync and "no retry" behaviors for `natsConnection_Connect()` and  allow the user to select appropriate mode by `natsOptions_SetRetryOnFailedConnect()`.

**Comment by kozlovic** [comment]
We could have something like: `natsOptions_SetRetryOnFailedConnect(stanConnOptions *opts, bool retry, bool blocking)` to cover all cases. My question is what about Publish and Subscribe calls while the connection is not yet connected for the first time. Should these calls fail or behave as during a reconnect event, I don't know.

**Comment by fmvin** [comment]
IMHO in user point of view Pub and Sub during first connection or reconnections should operate in similar way. If sub fails in first connection attempts user should think about retrying of subscription but don’t think about it in reconnection. It won’t be consistent behavior of cnats.
