### ISSUE TITLE
natsConnStatus entries name are too common and collides with other networking libs

### ISSUE THREAD

**Issue by yanivge** [nats-io/cnats#168]
found in release 1.7.6

typedef enum
{
    DISCONNECTED = 0, ///< The connection has been disconnected
    CONNECTING,       ///< The connection is in the process or connecting
    CONNECTED,        ///< The connection is connected
    CLOSED,           ///< The connection is closed
    RECONNECTING      ///< The connection is in the process or reconnecting

} natsConnStatus;

The enum item names are too common. 

maybe can change to NATS_st<STATUS> (NATS_st - nats status)
like this: 

typedef enum
{
    NATS_stDISCONNECTED = 0, ///< The connection has been disconnected
    NATS_stCONNECTING,       ///< The connection is in the process or connecting
    NATS_stCONNECTED,        ///< The connection is connected
    NATS_stCLOSED,           ///< The connection is closed
    NATS_stRECONNECTING      ///< The connection is in the process or reconnecting

} natsConnStatus;

**Comment by kozlovic** [comment]
I understand, but changing that now would possibly break users checking the connection status (using the current enum values) in their application. So not sure what's the next step is here.

**Comment by fmvin** [comment]
Vote for this issue. I face with this problem constantly.

**Comment by yanivge** [comment]
You can add a new enum with NATS prefix and wrap both with IFDEF
The new enum with the NATS will be the default and it will fix this issue for us and future users. 
users that download new version and getting compilation errors - will only need to add compilation flag

And you can maybe remove this duplication in the future

**Comment by kozlovic** [comment]
@yanivge and @fmvin I think PR #171 should address this issue. Let me know if this look ok to you.
