### ISSUE TITLE
Send buffers not cleared on nats-close

### ISSUE THREAD

**Issue by rudyjantz** [nats-io/cnats#188]
This is related to,
- Issue https://github.com/nats-io/cnats/issues/184
- PR https://github.com/nats-io/cnats/pull/187

Scenario:
A sender process uses publish to send data to a receiver process. Then that publisher immediately closes cnats.

Behavior:
The receiver does not always receive the message.

Expected behavior:
Unsure.
  - Without PR https://github.com/nats-io/cnats/pull/187, it's sort of expected that the publish may not complete. Though it's using the synchronous version of publish, cnats documentation states that data is buffered. Even with the send-asap option set to true, cnats is best effort. So it's understandable if the message does not arrive.
  - With PR https://github.com/nats-io/cnats/pull/187, it's less clear. That's mostly the purpose of raising this issue. Because `nats_CloseAndWait()` is designed to tear down cleanly, should that include completion of any buffered sends?

I've attached a small set of tests. There are 3 executables. 
- test_cnats.out is the "base" version.
- test_cnats_flush.out calls `natsConnection_Flush()` after publishing.
- test_cnats_sendasap.out uses `natsOptions_SetSendAsap(opts, true)`.
All 3 make use of PR https://github.com/nats-io/cnats/pull/187. The tests of interest are test-4 and test-5. To use,
```
$ make
./test_cnats.out 4 # should pass, and does
./test_cnats.out 5 # should pass with PR 187? fails about half of the time or more on my test machine
./test_cnats_sendasap 4 # should pass, and does
./test_cnats_sendasap 5 # should pass with PR 187? fails about half of the time or more on my test machine
./test_cnats_flush 4 # should pass, and does
./test_cnats_flush 5 # should pass, and does
```

If this is expected behavior, then please ignore. But in case it was overlooked, I wanted to raise it before PR https://github.com/nats-io/cnats/pull/187 is merged.

[cnats-pr-187-pub-then-disconnect-test.tar.gz](https://github.com/nats-io/cnats/files/2482700/cnats-pr-187-pub-then-disconnect-test.tar.gz)

**Comment by kozlovic** [comment]
`nats_Close()` or `nats_CloseWait()` (that is part of PR but may not be implemented) is not going to flush send buffers. Are you closing the connection in your publish process? If not, that would explain. The `natsConnection_Close()` call is flushing the send buffer before closing the TCP connection. There is still a risk that messages are not processed by the server. If you really want to ensure that all messages are received by the server before closing, I would recommend calling `natsConnection_Flush()` before `natsConnection_Close()` (not necessarily after each publish if you were publishing more than one message).

**Comment by rudyjantz** [comment]
I'm closing the connection in the publish process. I didn't use `natsConnection_Close()`, though. I relied on `natsConnection_Destroy()`. The docs say that destroy will close it under the hood: `* If not already done, this call first closes the connection to the server`. To be sure, I just added the `natsConnection_Close()` call as well, but it didn't help. So perhaps it is flushing the send buffer, but it's not processed by the server.

**Comment by kozlovic** [comment]
Yes, `natsConnection_Destroy()` is calling close internally so you don't have to add it explicitly. Again, calling Flush() before close/destroy would solve the problem. I can see if adding it internally in close is doable. We had such report for the go client: https://github.com/nats-io/go-nats/issues/333

**Comment by rudyjantz** [comment]
Got it. Thanks for the explanations. I'll leave it to you if you want to look into it.

**Comment by kozlovic** [comment]
If you want to check if PR #189 solves your issue, that would be great.

**Comment by rudyjantz** [comment]
You were quick. Yes, that indeed fixes it.
