### ISSUE TITLE
Track test coverage

### ISSUE THREAD

**Issue by seriousben** [nats-io/cnats#196]
Would be nice to integrate with coveralls.io maybe with something like https://github.com/JoakimSoderberg/coveralls-cmake

**Comment by kozlovic** [comment]
Thanks, will have a look when I have time. I do run in the build matrix a build with gcc and code coverage, but you have to go and manually check result.

**Comment by kozlovic** [comment]
@seriousben Thanks for the link! I had not been able to look at this until now, and it took me few tries to integrate with it but I think I got it. Thanks again for the advice and we have now a coverall badge :-)
