### ISSUE TITLE
How to read the Message from the NATS streaming queue

### ISSUE THREAD

**Issue by nginxsantos** [nats-io/cnats#200]
I am planning to store these records in NATS Streaming queue  (all the producer microservices will push to a common queue) and I want to fetch the entries on a predefined event. My requirement is not to get a notification when an entry is published, rather read from the queue when the time comes.

Can you please let me know how this will be done?

Thanks, Santos

**Comment by kozlovic** [comment]
@nginxsantos Please read documentation found [here](https://github.com/nats-io/cnats#streaming-subscriptions). Check all following paragraphs for the various type of subscriptions.
