### ISSUE TITLE
cnats/protobuf/nats

### ISSUE THREAD

**Issue by deji04** [nats-io/cnats#202]
Hi,

Do you have a documentation on how to use Protobuf with cnats? I wan to send over messages over NATS with cnats. Only available examples are for Golang. 

Thank you!

**Comment by kozlovic** [comment]
The protobuf library included in this project is for the internal use of the streaming API. There is no plan to have an encoder that sends protobuf messages as normal NATS messages. NATS messages payload are opaque (server does not look at the content), so you are free to set the content to anything you want as long as your receiver knows how to decode it.

**Comment by deji04** [comment]
So I've been trying to send a file (that is generated by google's protobuf from their examples, e.g. addressbook.data) thru cnats. And this is my code: https://shrib.com/#E237YjOu.km6YFqVMlbo
However, it only prints until the 'printf("Publishing messages on subject 'foo'\n");' and no message is received on the subscriber terminal. I've been using the syncsub.c for the subscription.

On my understanding, I can send a file in cnats. Is that correct? If so, am I on the right path on my code.
Or is Streaming Server is needed to send a file thru cnats?

Thank you!

**Comment by kozlovic** [comment]
@deji04 Sorry for the delay. NATS (and NATS Streaming) sets a limit on the size of a message payload to a default of 1MB. Although tunable, we generally don't recommend sending big messages in either product. You could split the file and send it in chunk, or send a link to a file that the receiver can download from a different transport.

**Comment by deji04** [comment]
Hi @kozlovic everything is okay now. What I did is write the messages to a file in the subscriber's end. Thank you for your support!
