### ISSUE TITLE
natsMutex_Lock function pthread_mutex_lock fail 

### ISSUE THREAD

**Issue by scorpion9111** [nats-io/cnats#204]
natsMutex_Lock function pthread_mutex_lock fail 
pthread_mutex_lock return 22
Have you ever encountered this problem?

**Comment by scorpion9111** [comment]
pthread_mutex_lock(m);
m != null

**Comment by kozlovic** [comment]
Can you provide a test application that shows this? Are you sure you are not creating too many objects that create threads underneath? For instance, creating too many asynchronous subscriptions would fail after a certain number of them because of the limit in number of threads the process can create.

**Comment by scorpion9111** [comment]
> Can you provide a test application that shows this? Are you sure you are not creating too many objects that create threads underneath? For instance, creating too many asynchronous subscriptions would fail after a certain number of them because of the limit in number of threads the process can create.

Not many threads
one doubtful point：
I frequently create and destroy timer of libnats in programs

**Comment by scorpion9111** [comment]
@kozlovic

**Comment by kozlovic** [comment]
@scorpion9111 Ok, I am getting confused now. Please provide some code to reproduce the issue. The library's mutex and timers are not exposed, so I really don't understand what you are referring to.

**Comment by kozlovic** [comment]
Only public APIs as documented [here](http://nats-io.github.io/cnats/index.html) or that you can find in installed header files should be used.

**Comment by scorpion9111** [comment]
I probably know the reason for this problem.
My program is like this：
receive some data from serial
receive a data，if the timer does not exist，create it，if the timer already exist，destroy it and create it
a possibility：
While _timerThread calls the timer callback function, my program destroys the timer，cause error
I change code：
receive a data，if the timer does not exist，create it，if the timer already exist，reset it
test it ,no errot at present
I will write a simple code to test again
thanks

**Comment by kozlovic** [comment]
But again, you should not be able to use NATS timers, etc.. those are internals.
