### ISSUE TITLE
Cnats can implement  to C++ ?

### ISSUE THREAD

**Issue by NantipatSoftEn** [nats-io/cnats#210]
Cnats can implement  to C++ ?  If not  
You can suggestion me  library Nats for c++

**Comment by loint** [comment]
yes, you can easily use c-nats for C++ project with CMake
https://github.com/nats-io/cnats/blob/master/CMakeLists.txt

**Comment by kozlovic** [comment]
The public headers all have:
```
#ifdef __cplusplus
extern "C" {
#endif
```
which should allow you to use the library in your c++ application.
