### ISSUE TITLE
error bad instruction `rep' in rpi2

### ISSUE THREAD

**Issue by heijiu** [nats-io/cnats#30]
/tmp/ccPXXpFE.s: Assembler messages:
/tmp/ccPXXpFE.s:204: Error: bad instruction `rep'
make[2]: *** [src/CMakeFiles/nats.dir/unix/mutex.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/nats.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

and

[ 88%] Building C object src/CMakeFiles/nats_static.dir/unix/thread.c.o
/tmp/ccvzGzHd.s: Assembler messages:
/tmp/ccvzGzHd.s:174: Error: bad instruction `rep'
make[2]: *** [src/CMakeFiles/nats_static.dir/unix/mutex.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/nats_static.dir/all] Error 2
make: *** [all] Error 2

**Comment by kozlovic** [comment]
Is it possible that you are building on ARM? If so, check https://github.com/nats-io/cnats/pull/29 which I merged yesterday that is supposed to disable spin lock.

**Comment by heijiu** [comment]
Thanks,RPI2 is ARM.
