### ISSUE TITLE
build error with visual studio 2015

### ISSUE THREAD

**Issue by dbskccc** [nats-io/cnats#45]
when build with visual studio 2015, snprintf can't define as macro

patch diff

 src/include/n-win.h | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/src/include/n-win.h b/src/include/n-win.h
index 9d46918..ab231b2 100644
--- a/src/include/n-win.h
+++ b/src/include/n-win.h
@@ -42,7 +42,10 @@ typedef int                 natsRecvLen;
 #define NATS_SOCK_GET_ERROR             WSAGetLastError()
 
 // Windows doesn't have those..
-#define snprintf    _snprintf
+#if _MSC_VER < 1900 
+#define snprintf _snprintf
+#endif
+
 #define strcasecmp  _stricmp
 
 int

**Comment by kozlovic** [comment]
@dbskccc Thanks for the report! Do you want to submit a PR? I can do it if you don't want, or don't have time. Thanks again!

**Comment by dbskccc** [comment]
@kozlovic please do it

**Comment by kozlovic** [comment]
Done! Thanks again!
