### ISSUE TITLE
TLS insecure skip verify by default?

### ISSUE THREAD

**Issue by shanna** [nats-io/cnats#47]
The `nats-io/go-nats` TLS connect implementation skips verification by default but I'm getting an SSL error for self signed certificates by default with a minimal cnats TLS client on this line: https://github.com/nats-io/cnats/blob/master/src/conn.c#L580

Should the client `rc` checks there be modified to match the Go implementation and ignore self signed certs?

**Comment by kozlovic** [comment]
It is true that `nats-io/go-nats` by default skip the verification, but you'll notice that we have a TODO there to make the secure version the default:

https://github.com/nats-io/go-nats/blob/master/nats.go#L793

So if we were to change that in the C client and later make the change to the Go client, we would have to revert the change in the C client. It also means introducing a new `natsOptions` setter to enable/disable the verification.

If you use self-signed certificates, you need to provide the trusted CA certificates using `natsOptions_LoadCATrustedCertificates()`.

Does it work for you if you use the above option or is it just that you find it inconvenient that you have to provide the CA for the C client and not the Go client?

**Comment by shanna** [comment]
I can fix my certificate bundle.  It's not self signed so I guess my bundle is wonky.

The cnats client behavior differing from nats-go isn't an issue on my end though I did expect them to be consistent since the README said it was a port of nats-go which is why I reported it. Is there are reason the Go client TODO hasn't been implemented? I can submit a patch if it's just removing the TODO and InsecureSkipVerify option.

**Comment by kozlovic** [comment]
Because it will break a lot of env where users just run with `nats.Secure()` ;-).

Let me check with few people here and see if we change c-nats to match Go, Go to match c-nats or leave the way it is.

And do let me know if you still have problem connecting c-nats to the server with TLS enabled.

**Comment by kozlovic** [comment]
By the way, if you specify `InsecureSkipVerify` to `false`, you would need to at least specify `ServerName`. The point of this code was to be able to connect with minimal config `nats.Secure())` in the `nats.Connect()` call. If we change `InsecureSkipVerify` to false, then we need the `ServerName` and the root CA if server uses self-signed certificates. In the end, that part of the `if` statement would then disappear and we would force the user to provide a TLS configuration in a way or another.

**Comment by shanna** [comment]
Yep I have a standalone Go websocket wss:// to NATS TLS proxy and I had to set ServerName to make a connection. I can't see how this is done with openssl cnats client if I use the `natsOptions_SetExpectedHostname(opts, "...");` option?

**Comment by kozlovic** [comment]
Since with `c-nats` I am performing server's cert verification, you may need to provide the root ca that verifies your server's certificate.

I am more and more inclined to fix the C client because even in the repo README.md, I specify that just using `natsOptions_SetSecure(true)`  may be enough to connect to a server using TLS. It is not really true if you still need to provide the root CA. I think that if *only* `natsOptions_SetSecure(true)` is specified and no other SSL/TLS related options are set, I should bypass server's certificate verification.

**Comment by kozlovic** [comment]
@shanna That being said, could you print the stack when you get the connect failure? Use this: `nats_PrintLastErrorStack(stderr);`.

**Comment by shanna** [comment]
Sure.

```
Error: 29 - SSL Error - (github.com/nats-io/cnats/src/conn.c:585): Server certificate verification failed: 19:self signed certificate in certificate chain:depth=3:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
Stack: (library version: 1.4.5)
  01 - _makeTLSConn
  02 - _checkForSecure
  03 - _processExpectedInfo
  04 - _processConnInit
  05 - _connect
  06 - natsConnection_Connect
```

**Comment by kozlovic** [comment]
Well, the message is pretty explicit. Error 19 is:
```
X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN: self signed certificate in certificate chain
    the certificate chain could be built up using the untrusted certificates but the root could 
    not be found locally.
```
There IS a self-signed certificate in the certificate chain. So you definitively need to provide the CA for those.

Some info: http://stackoverflow.com/questions/12180552/openssl-error-self-signed-certificate-in-certificate-chain

**Comment by shanna** [comment]
Except that if I verify the bundle with `openssl verify` I get an OK. That's why (right or wrong) I've been focusing on the client code since an openssl C client is the only client I'm having trouble with. Go (with InsecureSkipVerify: false) and Ruby both work. I've given up and I'm skipping verification in cnats for the time being.

**Comment by kozlovic** [comment]
You mean you get OK from this kind of command? `openssl verify -verbose -x509_strict -CAfile ca.pem cert_chain.pem`?

I am thinking of introducing a dedicated option to skip server certificate verification, and leave the default at it is today.
