### ISSUE TITLE
Example for pthreads in linux

### ISSUE THREAD

**Issue by umesh3034** [nats-io/cnats#52]
Hi,

Not an issue exactly.

Do you have an example using linux pthreads alone? I want to avoid using libevent and libuv.

I have another application which needs to send/recv NATS messages. I need to create 2 threads, one send thread and one receive thread which will do only NATS send and recv translation for the application in question. Do you have any examples?

Regards,
Umesh

**Comment by kozlovic** [comment]
Umesh, thank you for your interest in NATS C Client!

You don't have to use libevent nor libuv to use NATS C client. There are examples in the `examples` directory that show you how to use the various APIs. Now it looks like you need the same application to do sends and receives. Note that subscriptions can be asynchronous. For instance if you create a subscription like that:
```
s = natsConnection_Subscribe(&sub, conn, subj, onMsg, NULL);
```
This call does not block waiting for messages. Instead, when messages arrive, the callback `onMsg` in the above example is invoked from the C NATS internal threads. It means that you could have a loop sending messages after the above line.

The libevent's publisher example actually needs to do the send from a different thread and this sample program does use pthread (unless on running on Windows). If you simply just don't know how to create/join/destroy threads, you could have a look at [this](https://github.com/nats-io/cnats/blob/master/examples/libevent-pub.c#L7-L13) and the rest of this program to see how the thread is started then joined.

If you need more info, please describe better what your application needs to be doing.

**Comment by umesh3034** [comment]
Hi Kozlovic,

Thanks for the reply..
The pthread example given is fine, I can make changes to the code using the event libraries in example.

Below is my usecase. 

I have a C application to which i have integrated the CNATS static binary(libnats_static.a).

The Application needs to send info towards the NATS server, whenever it gets a certain packet. The NATS server will publish this message A to interested clients. The interested client will process this message A and reply back to the NATS server with message B. My application as a NATS client is subscribed to message B, once message B arrives my application processes this message and sends another packet to the network.




```

APPLICATION
with NATS client	NATS server		NATS client(application 2)
packetA -->message A-->	| -->message A-->	|  Process message A, send back message B
packetB	<--message B<-- | <--message B<--	|


```

I can do this in a couple of ways

1)
Have a "nats send thread", which receives messages(internal) from application and sends it towards the NATS server async. 
Have a "nats recv thread", which receives message from NATS server(subscrintion) and sends it to Application thread for further processing.
Much more work involved here.

2)
Call SYNC nats APIs directly from application, which will wait for message B to come in. Once message B is received, applcation will prcocess, that. Till that time application process is blocked.

Please provide your suggestions.

Regards,
Umesh

**Comment by kozlovic** [comment]
Umesh,

I assume that when you mention `packet` (A or B) you are not talking about NATS messages, right?
Can't your code receiving the packet A invoke directly `natsConnection_Publish()` with subject A and content of message A? Then have simply a `natsConnection_Subscribe(&sub, conn, "<subject B>", onMsgB, NULL)` call at the start of your application and whenever a message comes on subject B, the `onMsgB` callback function will be invoked from an internal NATS library thread, so you don't have to manage that thread.
That being said, if you find the use of a synchronous subscriber easier for your specific application, that works too!

**Comment by umesh3034** [comment]
Hi Kozlovic,

Thanks for the pointers!! 

packetA,B are not NATS messages. I am using natsConnection_SubscribeSync() at start of application. On receiving packet A, i do natsConnection_Publish() and then wait for reply at natsSubscription_NextMsg(). This works for me now. Maybe i need to think of scale. I need to so more prototyping.

Regards,
Umesh

**Comment by kozlovic** [comment]
@umesh3034 Good to know that you have a working solution for now! Thanks again for your interest in the NATS C Client.
