### ISSUE TITLE
Problems with natsConnection_ConnectTo and Windows

### ISSUE THREAD

**Issue by rFronteddu** [nats-io/cnats#53]
Hello, I was doing some tests with cnats on windows (vs2015) and I noticed that when a NATS server is not running, often the call to natsConnection_ConnectTo makes my program crash. My code is something as simple as:
    
    natsConnection *_pnc = NULL;
    int rc = 0;
    if ((rc = natsConnection_ConnectTo(&_pnc, NATS_DEFAULT_URL)) != 0) {
        printf("Connection failed...\n\n");
        natsConnection_Destroy(_pnc);
    }

with: 
Unhandled exception at 0x77049F83 (ntdll.dll) in launcher.exe: 0xC0000005: Access violation writing location 0x00000004.

In particular, the problem happens here:

```
natsMutex_Lock(natsMutex *m)
{
    // If gLockSpinCount > 0, the mutex has been created as as spin lock,
    // so we don't have to do anything special here.
    EnterCriticalSection(m);
}
```

(m is NULL)

Called by 

```
_cleanupThreadLocals(void) 
{
    void *tl = NULL;
    tl = natsThreadLocal_Get(gLib.errTLKey);
    if (tl != NULL)
        _destroyErrTL(tl);
    tl = NULL;
    natsMutex_Lock(gLib.lock);
....
```

**Comment by rFronteddu** [comment]
It may have been some silly mistake I made because making the connect to closer to the creation of the object that contained the connect to call fixed the problem.

**Comment by kozlovic** [comment]
Sorry, I do not quite understand your last comment.

I was not able to reproduce the issue. You should not have to destroy the connection since the `natsConnection_ConnectTo()` failed, but since you initialize `_pnc` to NULL, the destroy call should not crash.

**Comment by rFronteddu** [comment]
My bad, the thing that was crashing was the natsConnection_ConnectTo() call. The problem was probably somewhere else in my code since I fixed it by rewriting the object that contained the cNATS calls.
