### ISSUE TITLE
What about Android

### ISSUE THREAD

**Issue by rFronteddu** [nats-io/cnats#64]
Hello I was wondering if you tried compiling cnats for android.

**Comment by kozlovic** [comment]
I did not. Not sure if anybody in the community has.

**Comment by rFronteddu** [comment]
I'll give it a try this weekend.

**Comment by rFronteddu** [comment]
I made it, **I had to add #include <netinet/in.h> in n-unix** since without that include the compiler wasn't able to find the IPTCP macro in setops. I followed the ndk-build path since I am more familiar with it. It shouldn't be hard at all to make a cmake option for one more experienced with cmake.

I just compiled a simple main executable which uses the natsconnect method.  I still haven't tested the executable but I'll do that soon.

Android.mk -> https://pastebin.com/eLEC49DL
Application.mk -> https://pastebin.com/TRVs8WuH

**Comment by psantiagol** [comment]
Hi, I am compiling nats for Android with cmake. I managed to do so, but I had to manually comment this line in CMakeLists.txt set(NATS_EXTRA_LIB "rt -lpthread") as this lib is not available in Android. It would be nice if cmake workflow had into account this casuistic.

**Comment by kozlovic** [comment]
@psantiagol Could you try with removing just the `-lpthread` part? This was recently added to solve a CentOS build issue in this PR: https://github.com/nats-io/nats.c/pull/710.

**Comment by psantiagol** [comment]
Hi! in fact what is causing the failure is the rt one, as in Android environment isn't found such library.

**Comment by kozlovic** [comment]
@psantiagol Were you referring just to `NATS_EXTRA_LIB` or even `NATS_USE_PTHREAD` (the line above)?

Could you try something like:
```
else(APPLE)
   set(NATS_OS "LINUX")
   set(NATS_USE_PTHREAD "-pthread")
   if(NOT ANDROID)
     set(NATS_EXTRA_LIB "rt -lpthread")
   endif()
endif(APPLE)
```
and see if that works? If so, I will submit a PR. If you meant to also include the `NATS_USE_PTHREAD` line, please move the `if(NOT ANDROID)` a line above and let me know.

**Comment by psantiagol** [comment]
@kozlovic I tested both. In both cases compiled and ran correctly, so I assume set(NATS_USE_PTHREAD "-pthread") line is not necessary neither.

**Comment by kozlovic** [comment]
@psantiagol If it works with `NATS_USE_PTHREAD` I would keep this line to minimize the changes. I have no idea if removing the line we are removing for you is not going to cause issues to other people building on Android (that is, it may be a specific issue with your build environment). If other users report issues after making this change, we will have to change to a flag based solution (that is, an option that can be toggled ON/OFF to add this line). I will submit a PR today.
