### ISSUE TITLE
For users to use mingw64/32 in msys2

### ISSUE THREAD

**Issue by museghost** [nats-io/cnats#85]
Hi, there
I am a fan of gnatsd and its clients.  I am heavy user of cnat client library for high-throughput project.

Here is a tip for developer using mingw64, which I found it.

If you are a user, using mingw64/32 in msys2 environment, you should add the followings in CMakeLists.txt of the root folder.

My environments:
msys2 (latest one: 20161025 for x86_64, and getting the latest packages with msys2, pacman, dev tools)
mingw64 (gcc / g++ 6.3)

Around line number 75~77, you could find below

```cmake
elseif(WIN32)
  set(NATS_OS "_WIN32")
  set(NATS_PLATFORM_INCLUDE "win") 
```

in the above section, the followings are added.

```cmake
elseif(WIN32)
  message("WIN32")
  set(NATS_EXTRA_LIB "Ws2_32")
  set(NATS_OS "_WIN32")
  set(NATS_PLATFORM_INCLUDE "win")

```

Then, run cmake with -G "MSYS Makefiles" -->  mingw32-make.exe 
Finally it works

// Dear  Team,
if possible, could you please add the above in the CMakeLists.txt ?

Many thanks!

**Comment by kozlovic** [comment]
@museghost I have added it (except for `message("WIN32")` and hope it works for you. I have not installed msys2/mingw64 to test, but I have verified that it does not break the build using nmake.
Thanks for your contribution!
