### ISSUE TITLE
Problem compiling on ARM

### ISSUE THREAD

**Issue by rFronteddu** [nats-io/cnats#87]
Hello I was trying to compile CNATS for a specific ubuntu 14 arm64 box and when I get to the make install part I keep getting this error:

[  1%] Building C object src/CMakeFiles/nats.dir/unix/mutex.c.o
/tmp/ccjNLaiT.s: Assembler messages:
/tmp/ccjNLaiT.s:176: Error: unknown mnemonic `rep' -- `rep'
src/CMakeFiles/nats.dir/build.make:542: recipe for target 'src/CMakeFiles/nats.dir/unix/mutex.c.o' failed
make[2]: *** [src/CMakeFiles/nats.dir/unix/mutex.c.o] Error 1
CMakeFiles/Makefile2:983: recipe for target 'src/CMakeFiles/nats.dir/all' failed
make[1]: *** [src/CMakeFiles/nats.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I wonder if any of you has any Idea how to fix this. I was thinking of making my own simple makefile but I need to figure out how to handle forward declarations.

I also tried to compile it in another consumer arm 64 box and it works.

**Comment by kozlovic** [comment]
There was a fix long ago to not use `rep` instruction in spin lock on ARM: https://github.com/nats-io/cnats/pull/29. Wonder why this is not working for you. You could comment out that part of the code (all the spin lock think) and see if it works. If it does, we may add a CMAKE specific option in case `__arm__` is not sufficient (or maybe since you compile on 64, it would be `__arm64__` or something similar?)

**Comment by kozlovic** [comment]
It may be `__aarch64__`. Could you please try adding this and see if it works? If so, I will submit a PR for this fix.
```
#if !defined(__arm__) && !defined(__aarch64__)
```

**Comment by rFronteddu** [comment]
Ok, should I add it in mutex.c?

**Comment by kozlovic** [comment]
Yes, replace this [line](https://github.com/nats-io/cnats/blob/master/src/unix/mutex.c#L63) with this:
```
#if !defined(__arm__) && !defined(__aarch64__)
```

**Comment by rFronteddu** [comment]
Ok! Will let you know something tomorrow! Thanks for the support!

**Comment by rFronteddu** [comment]
They didn't let me touch the board today, Will try to do the test tomorrow.

**Comment by rFronteddu** [comment]
Yes! That fixed the issue!

**Comment by kozlovic** [comment]
Great! I will submit a PR later today.
