### ISSUE TITLE
natsConnection_SubscribeSync does not work with dynamically allocated string

### ISSUE THREAD

**Issue by cogmeta** [nats-io/cnats#89]
I am facing some strange behavior with natsConnection_SubscribeSync. It does not work with dynamically allocated string. Any explanation? Anything to do with heap vs stack allocation?

const chat *s="chatManager";
natsConnection_QueueSubscribeSync(&sub, conn, s, workerName); -- works

natsConnection_QueueSubscribeSync(&sub, conn,  "chatManager", workerName); -- works

char topic[128];
strncpy(topic, "chatManager", 128)
natsConnection_QueueSubscribeSync(&sub, conn,  topic, workerName);  -- does not work

chat *topic;
topic = (char*) malloc(sizeof(char) * 128);
strncpy(topic, "chatManager", 128);
natsConnection_QueueSubscribeSync(&sub, conn,  topic, workerName);  -- does not work

**Comment by kozlovic** [comment]
@cogmeta What do you mean by "does not work"? Do you have an actual test case to provide? I have just tried with a copy into a char array and it works fine, meaning that the queue member is able to receive a message.

**Comment by cogmeta** [comment]
I just made following changes to queuegroup.c in ./examples.

 diff queuegroup.c queuegroup_bug.c 
62,63c62,68
<         else
<             s = natsConnection_QueueSubscribeSync(&sub, conn, subj, name);
---
>         else {
>         char *topicName;
>         topicName = (char*) malloc(sizeof(char) * 128);
>         strcpy(topicName, "chatMananger");
>         printf("topicName=>[%s]\n", topicName);
>         s = natsConnection_QueueSubscribeSync(&sub, conn, topicName, name);
>       }

$gcc -o queuegroup queuegroup.c -lnats
$ ./queuegroup -sync
Listening synchronously on 'chatManager' with name 'worker'.
In Msgs:         1 - In Bytes:        11 - Delivered:         1 - Pending:     0 - Dropped:     0 - Reconnected:   0


gcc -o queuegroup_bug queuegroup_bug.c -lnats
$ ./queuegroup_bug -sync
Listening synchronously on 'chatManager' with name 'worker'.
topicName=>[chatMananger]
Error: 26 - Timeout
Error: 26 - Timeout - (sub.c:545): Timeout
Stack: (library version: 1.7.0)
  01 - natsSubscription_NextMsg

**Comment by kozlovic** [comment]
I think you have a typo in your topic name. I think you expect it to be `chatManager`, but you wrote `chatMananger`. I bet you are sending to `chatManager` ;-)

**Comment by kozlovic** [comment]
Run `gnatsd -DV` and check the `SUB` protocol message. Then send a message and check the `PUB` protocol message.

**Comment by cogmeta** [comment]
Thanks for pointing out typo. I hope that resolves it. Closing it for now..

**Comment by kozlovic** [comment]
I first did by hand and it worked fine, then copied yours and realized that indeed I was not receiving the message, until I spotted the typo. I am confident that it will work.
