### ISSUE TITLE
 undefined reference to `clock_gettime' when build CentOS 6.7

### ISSUE THREAD

**Issue by jmptrader** [nats-io/cnats#9]
Dear,

My system is : CentOS 6.7 x86_64
uname -r       : 2.6.32-573.7.1.el6.x86_64

When build the library/examples/testsuite, I get:

```
[ 79%] Built target nats_static
Scanning dependencies of target nats-publisher
[ 81%] Building C object examples/CMakeFiles/nats-publisher.dir/publisher.c.o
[ 82%] Linking C executable nats-publisher
../src/libnats.so: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[2]: *** [examples/nats-publisher] Error 1
make[1]: *** [examples/CMakeFiles/nats-publisher.dir/all] Error 2
make: *** [all] Error 2
```

I not experience in cmake, but manually in link.txt files, I add at end :

```
                    -Wl,--no-as-needed -lrt
```
**My build problem solved**

```
   ../examples/CMakeFiles/nats-publisher.dir/link.txt
   ../examples/CMakeFiles/nats-queuegroup.dir/link.txt
  ../examples/CMakeFiles/nats-replier.dir/link.txt
  ../examples/CMakeFiles/nats-requestor.dir/link.txt
  ../test/CMakeFiles/testsuite.dir/link.txt
```

JM

**Comment by kozlovic** [comment]
JM,

Thanks for the report. I had the same issue when building on Travis (using on older libc that I have on my Ubuntu image). I had disable the use of clock_gettime when building on Travis as a work-around until I found how to fix that with CMake. I think I did. The build now passes on Travis. Could you do me a favor and checkout the 'fix_clock_gettime' branch, build and see if it works for you? If it does, I will merge it to master.

**Comment by jmptrader** [comment]
Ivan,

In my system is solved the problem. 

I add to end: 

    -Wl,--no-as-needed -lrt


in link.txt file.

The cnats-lib, examples, suite build & run ok.

Thanks,
JM

Enviado desde mi BlackBerry de Movistar

-----Original Message-----

**Comment by kozlovic** [comment]
JM,
I understand that if you manually modify the link command line, then it will work. But I want the change to be made in the CMake files so that you don't have to manually modify anything. So I am not sure if you mean that you have tried the branch and it now works for you without any manual modification, or it does not work and you still have to modify manually the link command. Could you please clarify?

**Comment by jmptrader** [comment]
Ivan,

OK, I will test this.

JM 


Enviado desde mi BlackBerry de Movistar

-----Original Message-----

**Comment by kozlovic** [comment]
JM,

Have you had a chance to test the branch? 

Thanks!

**Comment by kozlovic** [comment]
JM, I have merged the changes into master. Hopefully, this solves the problem in your environment. If not let me know! I will close the issue for now, do not hesitate to re-open if needed.
Thanks!

**Comment by jmptrader** [comment]
Ivan;
 
Yes! Please closed it!

Thanks,
JM  


Enviado desde mi BlackBerry de Movistar

-----Original Message-----
