### ISSUE TITLE
Make examples more pedagogical

### ISSUE THREAD

**Issue by dbeecham** [nats-io/cnats#99]
Examples (in /examples) are currently written in a sort of tech-demo-style (aka look-how-cool-this-is-style). I would rather see examples with a pedagogical focus ("see how easy it is to get started"-style). Currently, when you read the examples, you zoom back and forth between `examples.h` and the source file, and you try to simplify the example to it's bare bones. Not super helpful.

A couple of things I'd like to see:
* Remove argument parsing - we're not interested in running the program for real, and we can do argument parsing ourselves.
* Inline and remove examples.h - this file only serves a purpose if you're looking to compile all of the examples... actually, it mostly looks lazy...
* Split `subscriber.c` into `asyncsubscriber.c` and `syncsubscriber.c`. People like specific examples. General logic is not "example"-material.
* Drop `printStats`. Create a `stats.c` where you can flash with your awesome statistics instead! Actually, you should create a `benchmark/`-folder and put stats-stuff in there, that way you can be flashy and pedagogical at the same time!

If tech-demo-style is your thing, then don't let me get in the way, but I think that programmers getting to know your library (people like me) would be grateful to have simple bare-bones look-how-easy-this-is no-frills examples to start off with. An example with 10 lines of code would scream "this is easy" - which is something everyone enjoys.

**Comment by kozlovic** [comment]
@dbeecham Thank you for the feedback! The examples in that directory are actually built and can be used to send/receive messages, etc.. and also used to benchmark as you suggests.

I could add a `getstarted` directory under examples. I could add very basic `sub.c`, `asyncsub.c`, etc... that hardcode subject, expect to connect to default URL, etc... Anything specific you would think should be covered under that directory?

**Comment by dbeecham** [comment]
Yes! That would be awesome.

I feel like one of each of the basic methodologies is enough. A subscriber, a publisher, a requester and a replier, and an example of async. Queue groups are basically just... pubsub... but with the queue option set, not sure an example is really needed for that.

**Comment by kozlovic** [comment]
Will do. And thanks because when trying to create a sample for `natsConnection_PublishMsg()`, I realized that there is a bug there! I guess nobody is using this variant. Will have a separate fix for that and continue on the `getstarted` addition!

**Comment by kozlovic** [comment]
This function was somehow not part of the testsuite, at least not testing that function itself. Will correct that.

**Comment by kozlovic** [comment]
@dbeecham Again, thank you for the interest and please check the PR #101 and let me know if you would want to add more basic examples. Also, let me know if current format is ok or what you would change.

**Comment by dbeecham** [comment]
That's *perfect*! Awesome! Thank you!
